### ISSUE TITLE
Computation of the Pig model with optional offsets 

### ISSUE THREAD

**Issue by aaa34169** [OpenMA/openma#2]
Thigh offset, shank offset and tibialRotation angle are optional parameter , they can get closer the model with anatomy. 
These parameters are calculated during static calibration with the Knee Aligmenent device. 
Well established gait labs use the KAD :-) 
In consequence,  
- the  openMA chord function should accept an additional parameters ( ie, shank and thigh offset)  
- the openMA pig configurator shoudl consider an untorsioned tibia

**Comment by Alzathar** [comment]
Most of the work is done and validated in the branch [plugin-gait-kad](https://github.com/OpenMA/openma/tree/plugin-gait-kad). 

**Important** : Improvement must be done about the management of the (un)torsioned tibia. There is a difference in the computation of the ankle kinematics for the KADMed variant. There is a known issue on Vicon side about this.

**Comment by Alzathar** [comment]
Since the commit aff9937, the computation of the joint kinematics for the model plug-in gait is completed and validated against reference data for all variants (Basic, KAD, and KADMed).
