### ISSUE TITLE
Implement support for the FORCE_PLATFORM:ZERO c3d parameter

### ISSUE THREAD

**Issue by nilsbetzler** [OpenMA/openma#43]
The FORCE_PLATFORM:ZERO parameter can be used to provide a range of frames where the force plate is unloaded and that can be used to determine a zero baseline for each plate, see [here](https://www.c3d.org/HTML/default.htm?turl=zero.htm).

As many force plates output some residual force values even after zeroing the amplifier, it would be useful if OpenMA could read the frame numbers and apply them accordingly.

No baseline subtraction should be performed if the parameter does not exist or is set to an array containing [0,0].

**Comment by Alzathar** [comment]
The commit c39d381c5ffd1f106e4848e6ea2462ff5d7225d9 introduced methods to configure and enable/disable the usage of a soft reset for the force platform. This soft reset has an effect on the computed wrench.

The methods implemented are the following:
```
// Enable/disable soft reset
ma::instrument::ForcePlate::setSoftResetEnabled()
ma::instrument::ForcePlate::isSoftResetEnabled()
// Configure
// WARNING: Indices to give must be 0-based
ma::instrument::ForcePlate::setSoftResetSamples()
ma::instrument::ForcePlate::softResetSamples()
```
The content of the C3D parameter `FORCE_PLATFORM:ZERO` is correctly managed (see commit 82780fc481d48ab7f1815caf0022705f0f5f3427).

**IMPORTANT**: By default, the soft reset is not enabled.

Under Python you can enable it with the following code:
```
trials = ma.io.read('myfille.ext')
fps = trials.findChildren(ma.instrument.T_ForcePlate)
for fp in fps:
    fp.setSoftResetEnabled(True)
```

Does it reply to your need?

**Comment by Alzathar** [comment]
This issue is closed as it was resolved more than one month ago and the original reporter did not complain about any problem with the proposed solution.
