### ISSUE TITLE
Unable to install, no INCLUDES exists

### ISSUE THREAD

**Issue by marnunez** [OpenMA/openma#60]
After successfully compiling OpenMA with the Python bindings, executing `sudo make install`

throws
```bash
CMake Error at 3rdparty/eigen3/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/home/chofita/Documentos/Proyecto_FINAL/openma/3rdparty/eigen3/INCLUDES".
```
which in effect, does not exist.

**Comment by Alzathar** [comment]
It is important to mention that the installation step copies only the C++ files headers and associated libraries. It gives a simple way use OpenMA as an external dependency for a custom C++ project. The bindings are not installed or packaged within this step.

**Comment by marnunez** [comment]
Aha. But shouldn't the bindings be installed as well, like in BTK? So, to clarify, the only thing left to do is to copy everything under the "python" folder in "bindings" to the system's python path, right?

**Comment by Alzathar** [comment]
To use OpenMA inside Python without a local include like:

```
import sys
sys.path.append('my_openma_build_path/swig/python/openma');
```

you can install manually the Python bindings in your site-packages folder: http://stackoverflow.com/questions/4933224/how-to-install-a-python-library-manually

The reason is that OpenMA has not yet a `setup.py` file.

**Comment by marnunez** [comment]
Awesome! Thanks!

**Comment by Alzathar** [comment]
I let give you a try. Can you close the ticket if it works as expected?

**Comment by marnunez** [comment]
Works! I'll start playing with the bindings, and I'll slowly transition my other projects from BTK to OpenMA. Closing the ticket. Nevertheless, could this be turned into a low priority feature?
