### ISSUE TITLE
Building on Windows 7 with minGW 5.3.0

### ISSUE THREAD

**Issue by mdkdy** [OpenMA/openma#74]
I tried to build OpenMA on Windows 7 using minGW 5.3.0.

So it works fine until 82% (mingw32-make from cmd). Then I receive errors:

 

>  [ 82%] Building CXX object modules/io/CMakeFiles/io.dir/src/file.cpp.obj
> In file included from C:\libs\openma-master\modules\io\src\file.cpp:36:0:
> C:/libs/openma-master/modules/io/include/openma/io/file_p.h:48:4: error: #error
> Missing header to build the File class (memory mapping not found).
>    #error Missing header to build the File class (memory mapping not found).
>     ^
> C:/libs/openma-master/modules/io/include/openma/io/file_p.h:121:5: error: 'HANDL
> E' does not name a type
>      HANDLE m_File;
>      ^
> C:/libs/openma-master/modules/io/include/openma/io/file_p.h:122:5: error: 'HANDL
> E' does not name a type
>      HANDLE m_Map;
>      ^
> C:/libs/openma-master/modules/io/include/openma/io/file_p.h: In member function
> 'bool ma::io::MemoryMappedBuffer::isOpen() const':
> C:/libs/openma-master/modules/io/include/openma/io/file_p.h:95:58: error: 'const
>  class ma::io::MemoryMappedBuffer' has no member named 'm_File'
>      bool isOpen() const _OPENMA_NOEXCEPT {return !(this->m_File == _OPENMA_MMFI
> LEBUF_NO_FILE);};

etc...
So what's going on? Can I use this compiler?

**Comment by Alzathar** [comment]
Your problem should be fixed now. Can you update the code and test on your side?

**Comment by mdkdy** [comment]
It compiles now, thank you.
So there are six shared libs in result.
I need to read data from c3d file. Can I ask here if the io module is the one I should use or I need others?

**Comment by Alzathar** [comment]
If you use shared libraries and your goal is to read a C3D file, you need 4 libraries:
 - `openma_io.dll`: contains the C3D parser`
 - `openma_base.dll`: base class for all modules
 - `openma_instrument.dll`: contains force plate definitions that could be stored in a C3D file
 - `openma_math.dll`: mathematical operations used by the force plates (e.g wrench computation, downsampling, soft reset).

**Comment by Alzathar** [comment]
Closed because the issue was fixed. Please open another issue for any other concerns.

**Comment by axtrend** [comment]
I managed to open a file using `ma::io::File` class (`isOpen` returned true). I am trying to compehend the list of classes but I am having a hard time to actually import from this file a store data in some data structure (I need positions of vertices in each frame).
